language: node_js
cache: yarn

env:
  global:
    secure: wtBX98vubHC+/5aXLUB3fNZKmnrpLnpgZkbUrfWuq01fEKk/CmL64ArkoqrGOffUhFKRemjgXVPGLF118AZuyS/dW4o05v7KOuBHt7SehhdgO8AVlQ5DVrEQm3gVFNYcusaMRP1eJpSwekHqF7grHk1VTr/uNj01OyAExKynmn6rHJNa/KijRuHsTBEQL7drLOyAHUvodq0c2fclW71H85cTaHXC+NPzydWCWn3k4Z6sGEkQCOIG+v0skWEnN1uyt5MJ89a9WPF8qz/LqVolXKmWHVowpagV2KUQpeZs8Kkao93reWs/MocTXm82gcffBdhqozv6xN55bC1BoJ0oB/S7RHk1dWRgTcPj1hkX5H4X5S8COT9/5FE2tw74jN6mLSKdRy3nNOQZPZuXOn2jlkl2n+b0IwwXBXLfn3ks18AX1Y4kAQBsfPGPM7zPX742Z8cR2rW41aVwWFDVhqI4ITBWOzUC6Cvlm8JT+eADYG5R9sodxS9jEDOH/9Gjx4xRPQK7+Q909x1XmGnVOSFlsCLHT8f7y1mPWTzPT5x57rhkD4BmX4bb0+RAVvDSiVIcko9QznK9lGSNgSX4+Y/sZHW2DHdbo2SdDmLxwUDGAgHXJ3mQNsI0ojAIb/b0d9Ybw4OuWgdMu8aaB+vZuqm1AD57oNomEXnHeMkFlVT42ho=

jobs:
  include:
  # Test latest ZMQ versions on Linux and macOS.
  - os: linux
    node_js: 9.7

  - os: linux
    node_js: 8.8

  - os: linux
    env: ALPINE_CHROOT=true
    sudo: required

  - os: osx
    node_js: 9.7
    env: NO_COMPAT_TEST=true
    osx_image: xcode9.3beta

  - os: osx
    node_js: 8.8
    env: NO_COMPAT_TEST=true
    osx_image: xcode9.3beta

  # Test shared libraries on Linux and macOS.
  - os: linux
    node_js: 9.7
    env: ZMQ_SHARED=true NO_COMPAT_TEST=true
    addons: {apt: {packages: libzmq3-dev}}

  - os: osx
    node_js: 9.7
    osx_image: xcode9.3beta
    env: ZMQ_SHARED=true NO_COMPAT_TEST=true

  # Test older version branches of ZMQ.
  - os: linux
    node_js: 9.7
    # Previous stable version on 4.2 branch.
    env: ZMQ_VERSION=4.2.2

  - os: linux
    node_js: 9.7
    # Latest stable version on 4.1 branch.
    env: ZMQ_VERSION=4.1.6
  - os: linux
    node_js: 9.7
    # Version of libzmq3 on Ubuntu Trusty.
    env: ZMQ_VERSION=4.0.4

  # Publish all binaries for Linux and macOS.
  - stage: publish binaries
    node_js: 9.7
    os: linux
    script: script/ci/release.sh

  - stage: publish binaries
    node_js: 9.7
    os: osx
    osx_image: xcode9.3beta
    script: script/ci/release.sh

  # Publish chroot cross-compiled binaries for Alpine Linux.
  - stage: publish binaries
    node_js: 9.7
    os: linux
    env: ALPINE_CHROOT=true
    script: script/ci/release.sh

  # Publish cross-compiled binaries for arm & arm64.
  - stage: publish binaries
    node_js: 9.7
    os: linux
    env: ARCH=arm TRIPLE=arm-linux-gnueabihf GCC=4.8
    install: script/ci/cross-install.sh
    script: script/ci/cross-release.sh
    addons: {apt: {packages: [gcc-4.8-arm-linux-gnueabihf, g++-4.8-arm-linux-gnueabihf]}}

  - stage: publish binaries
    node_js: 9.7
    os: linux
    env: ARCH=arm64 TRIPLE=aarch64-linux-gnu GCC=4.8
    install: script/ci/cross-install.sh
    script: script/ci/cross-release.sh
    addons: {apt: {packages: [gcc-4.8-aarch64-linux-gnu, g++-4.8-aarch64-linux-gnu]}}

  # Publish package to NPM.
  - stage: publish package
    script: skip
    os: linux
    deploy:
      provider: npm
      email: r.w.timmermans@gmail.com
      api_key:
        secure: rg8GpeS20asj3JcgmfQpumBc1JV44hliyCIW3Y+rN/5gaurkm87K8MGVsNTVwwsdWyBFGjfGEYUhXF+H9q/OMLRchHqkfW6y7jzbWQx5QP5srbf7J8uWGIytKzJbX6yt41kHzk+FKFU2XAzrIP+51tvZiqBdpkkKCA/KdKG779mH04uphxcuaGtiEtqGhXdNe494r4ux727hvATRJwnGO6JvDzD6aM92i5SZdM/xKIPt+1KNRX92TIWj/op5XkpwvkPZjAERdOiHB052GM0mgaMxZiJdO0Xb5FeTh/1SXZXYE+XPIY4Sm3Pa75Kk3UFt5nI4DKFhl6V8UwOPAHiIFBZJPe/avOxPejHzwLxO3nBWEboiuc0OWds16x1NJsSLGk3CtDcFl6Zkanh8EFmyy7LMUuR1MEjY6+azQgTibVB2ynqN1MKYkxl/aDJB0xYtabDgaptiM5ITaMNUR7pUG4VRQkvi6L5TfMdzI8/mwxkjMnnVnFef8OGw5i0SRJMpEXeohrgCjkUN+uxpo+FIzPDf/tano35wgh/LYDbXNMfdEgd1L9MkOIS32vN46HbAbjrhSNIxK2u8PsOB07hPjmiFkoGRzrgg0veJ194FZ0k8LEJtqmDMCCMBaFiO1TuTHDNyGzAsR17Upk7/qZKeH/EPDhvbycH4hWvvri29yrI=
      on:
        tags: true

stages:
- name: test
- name: publish binaries
  if: tag IS present
- name: publish package
  if: tag IS present

install:
- travis_retry script/ci/install.sh

script:
- travis_retry script/ci/test.sh
