environment:
  GH_TOKEN:
    secure: 6V8UzhSBNiXKcwNF1cTFaqTZaX/YVUWutdbluQVdXPlUn1u9G+cd1XTgyZQDmD+4
  matrix:
  - node_js: 8.6

platform:
- x64
- x86

build: off

install:
- ps: Install-Product node $env:node_js $env:platform
- appveyor-retry call sh script/ci/install.sh

test_script:
- appveyor-retry call yarn test

deploy_script:
- IF "%appveyor_repo_tag%"=="true" sh script/ci/release.sh
